vtex-sites/base.store

- cypress.json
- cypress/fixtures/example.json
- cypress/integration/seo.test.js
- cypress/plugins/index.js
- cypress/support/commands.js
- cypress/support/index.js
- package.json
- yarn.lock
This PR adds cypress tests to SEO tags
> Chore cypress tags

- gatsby-browser.js
- gatsby-ssr.js
- package.json
- src/pages/404.tsx
- src/pages/500.tsx
- src/pages/[slug]/p.tsx
- src/pages/account.tsx
- src/pages/index.tsx
- src/pages/login.tsx
- src/pages/offline.tsx
- src/pages/s/[...].tsx
- src/pages/{StoreCollection.slug}/[...].tsx
- src/pages/{StoreCollection.slug}/index.tsx
- src/pages/{StoreProduct.slug}/p.tsx
- src/views/Layout.tsx
- src/views/collection/hooks/useCollection.ts
- src/views/collection/index.tsx
- src/views/home/index.tsx
- src/views/product/index.tsx
- src/views/search/hooks/useSearch.ts
- src/views/search/index.tsx
- yarn.lock
The world is not ready for react 18, let's rollback to react 17
> Migrate to React 17

- src/pages/[slug]/p.tsx
Simple typo correction
Self-explanatory
Search to see if this variable is used anywhere else that wasn't modified, test if PDPs are still working with client-side rendering.
No references to share
> Fixed typo: browerData -> browserData

- __generated__/CollectionSearchQuery.graphql.ts
- __generated__/FacetedFilter_facets.graphql.ts
- __generated__/FullTextSearchQuery.graphql.ts
- cypress/integration/plp.test.js
- src/components/search/FacetedFilter/FacetedFilter.module.css
- src/components/search/FacetedFilter/FacetedFilter.tsx
- src/components/search/FacetedFilter/index.ts
- src/components/sections/ProductGallery/ProductGallery.tsx
- src/typings/schema.graphql.d.ts
This PR adds a very simple faceted filter component so we can filter the page and add tests for page filtering
Take a look at the tests written. Also, try to toggle the facets yourself at the deploy preview
> feat: Add search filters

- cypress/integration/plp.test.js
- src/components/product/ProductSummary/ProductSummary.tsx
- src/components/search/Sort/Sort.tsx
- src/components/search/Sort/index.tsx
- src/components/sections/ProductGallery/ProductGallery.tsx
- src/typings/schema.graphql.d.ts
This PR adds search sorting component and tests so we can test the behavior of the store
Open a plp and apply sort. Make sure the behavior is correct. Also, take a look at the tests
> feat: Search Sort

- README.md
> Change reference to storecomponents.store to base.store

- package.json
- src/components/sections/ProductGallery/ProductGallery.tsx
- src/components/sections/ProductGallery/ProductGalleryPage.tsx
- src/views/collection/index.tsx
- src/views/product/hooks/useProduct.ts
- src/views/search/index.tsx
- yarn.lock
Upgrades SWR to 1.x since now they promise smaller bundle sizes
> chore: Upgrade SWR to 1.x

- README.md
<em>Tweaks `readme.md` file to instruct usage of `yarn develop` instead of `gatsby develop` command </em>
> Tweaks README.md

- src/typings/schema.graphql.d.ts
<em>Considering the context, what is the problem we'll solve? Where in VTEX's big picture our issue fits in? Write a tweet about the context and the problem itself.</em>
> fix: new schemas

- src/components/cart/CartItem/CartItem.tsx
- src/components/cart/CartSidebar/CartSidebar.tsx
- src/components/cart/CartToggle/CartToggle.tsx
- src/components/common/Navbar/Navbar.tsx
- src/components/product/ProductSummary/ProductSummary.tsx
- src/components/search/FacetedFilter/FacetedFilter.tsx
- src/components/sections/ProductDetails/ProductDetails.tsx
- src/components/ui/Button/Button.tsx
- src/components/ui/Button/index.tsx
- src/components/ui/Toast/Toast.tsx
Signed-off-by: Arthur Andrade <arthurfelandrade@gmail.com>## What's the purpose of this pull request?
<em>This PR add Store-UI Button in base.store</em>
<em>To add the Button this PR replaces all vanillas HTML buttons with store.ui Button.</em>
> feat: Add Button component

- src/components/product/ProductSummary/ProductSummary.tsx
- src/components/ui/DiscountBadge/DiscountBadge.tsx
- src/components/ui/DiscountBadge/index.tsx
<em>This PR does a refactor in badge component, creating a DiscountBadgeComponent with isolated logic</em>
<em> Was created a DiscountBadgeComponent with the logic to calculate the discount percentage and format the value.</em>
> refactor: put DiscountPriceBadge in pattern

- package.json
- yarn.lock
While testing or running the lighthouse audit, we were starting the server. Turns out sometimes you just want to run the tests without setting up the server. 
This PR simplifies the process of testing by making the test script only open cypress and test, requiring the user to start the server before testing.
> chore: Simplify commands

- README.md
- lighthouserc.js
<em>Considering the context, what is the problem we'll solve? Where in VTEX's big picture our issue fits in? Write a tweet about the context and the problem itself.</em>
> Disable csp-xss check on lighthouserc.js

- cypress/integration/plp.test.js
- src/components/sections/ProductGallery/ProductGallery.tsx
- store.config.js
This PR changes the VTEX account used by base store to storeframework.
> chore: updated account used by base store to "storeframework"

- src/styles/global.scss
- src/styles/pattern-library.scss
- src/styles/resets/_modern-normalize.css
- src/styles/resets/reset.css
- src/styles/typography.scss
- Adds reset and fix issues on `main-styled` branch.
- Adds basics setup to `main-styled`  branch
- https://github.com/sindresorhus/modern-normalize
- https://web.dev/tap-targets/?utm_source=lighthouse&utm_medium=node
- https://web.dev/font-best-practices/
- https://tailwindcss.com/docs/preflight#border-styles-are-reset-globally
> Chore: General style updates/fixes

- src/components/common/SearchInput/SearchInput.tsx
- src/components/ui/DiscountBadge/DiscountBadge.tsx
- src/components/ui/DiscountBadge/discount-badge.scss
- src/pages/pattern-library.tsx
- src/styles/colors.scss
- src/styles/global.scss
- src/styles/grid.scss
- src/styles/vendors/include-media_overwrite.scss
> Chore: style main updates

- src/components/cart/CartToggle/CartToggle.tsx
- src/components/cart/CartToggle/cart-toggle.module.scss
- src/components/cart/CartToggle/cart-toggle.scss
- src/pages/pattern-library.tsx
This PR styles the cart-toggle component
Add a stylesheet for cart-toggle and implement a style like the [Figma Prototype](https://www.figma.com/file/wS0Kek1aSzIRl20jdtnSsL/Alpha-Version?node-id=0%3A1)
> feat: Add cart button styles

- src/components/sections/Hero/Hero.tsx
- src/components/sections/Hero/index.tsx
- src/images/config.js
- src/pages/index.tsx
This PR adjusts implementation of Hero component.
This PR call a Implementation of Hero in section folder for integrate with CMS, and use Image component.
> fix: add hero in section

- src/components/ui/BuyButton/BuyButton.tsx
- src/components/ui/BuyButton/index.tsx
- src/pages/pattern-library.tsx
Creates the [BuyButton](https://vtex-dev.atlassian.net/browse/FSSS-89) component using the FastStore button as base.
This component should only be used on the PDP.
> Feat: Creates BuyButton Component

- src/components/sections/Hero/Hero.tsx
- src/components/sections/Hero/index.tsx
- src/components/ui/Tiles/Tile.tsx
- src/components/ui/Tiles/Tiles.tsx
- src/components/ui/Tiles/index.tsx
- src/images/config.js
- src/pages/index.tsx
Updates the `main-styled` branch with the code in the `master` branch.
> Chore: Updates Main Styled

- src/components/ui/Alert/Alert.tsx
- src/components/ui/Alert/alert.scss
- src/pages/pattern-library.tsx
- src/styles/colors.scss
This PR aims to tweak the Alert style.
> Chore: Tweaks Alert style

- src/components/sections/Hero/Hero.tsx
- src/components/ui/Hero/Hero.tsx
- src/components/ui/Hero/hero.scss
- src/styles/global.scss
- src/styles/typography.scss
- stylelint.config.js
This PR styles the Hero component
Add a stylesheet for hero and implement a style like the [Figma Prototype](https://www.figma.com/file/wS0Kek1aSzIRl20jdtnSsL/Alpha-Version?node-id=0%3A1)
> Feat: Style Hero component

- src/components/sections/BannerText/BannerText.tsx
- src/components/sections/BannerText/banner-text.scss
- src/styles/typography.scss
This PR styles the BannerText component
Add a stylesheet for banner text and implement a style like the [Figma Prototype](https://www.figma.com/file/wS0Kek1aSzIRl20jdtnSsL/Alpha-Version?node-id=0%3A1)
> feat: Add banner text

- gatsby-browser.js
- gatsby-ssr.js
- src/Layout.tsx
Attempt to follow lighthouse opportunities of improvement
> Attempt to preconnect to gstatic

- src/components/product/ProductCard/ProductCard.tsx
- src/components/product/ProductCard/index.tsx
- src/components/product/ProductCard/product-card.scss
- src/components/product/ProductGrid/ProductGrid.tsx
- src/components/product/ProductSummary/index.tsx
- src/components/ui/DiscountBadge/discount-badge.scss
- Renames ProductSummary to ProductCard
- Creates variant="horizontal" and "vertical"
- Adds `showActions` prop to hide Cart Button
> Chore: Style Product Card variant

- gatsby-browser.js
- gatsby-ssr.js
- src/components/sections/ProductDetails/ProductDetails.tsx
Clear code, removes unused code.
> Chore: Remove unused code

- src/components/product/ProductCard/ProductCard.tsx
- src/components/sections/ProductDetails/ProductDetails.tsx
- src/components/sections/ProductDetails/product-details.scss
- src/components/sections/ProductShelf/product-shelf.scss
- src/components/sections/ProductTiles/ProductTiles.tsx
- src/components/ui/AspectRatio/AspectRatio.tsx
- src/components/ui/AspectRatio/aspect-ratio.scss
- src/components/ui/AspectRatio/index.tsx
- src/components/ui/Tiles/tiles.scss
This PR intends to add the `AspectRatio` component.
- [Chakra UI](https://chakra-ui.com/docs/layout/aspect-ratio);
- [Radix UI](https://www.radix-ui.com/docs/primitives/components/aspect-ratio);
- ["Let's learn about aspect ratio in CSS"](https://ishadeed.com/article/css-aspect-ratio/);
- [CSS Tricks](https://css-tricks.com/almanac/properties/a/aspect-ratio/).
> feat: Add AspectRatio component

- gatsby-node.js
- package.json
- src/server/index.js
> chore: Use onPreInit for partytown

- src/components/common/SearchInput/search-input.scss
- src/components/ui/QuantitySelector/quantity-selector.scss
- src/components/ui/SkuSelector/sku-selector.scss
- src/pages/pattern-library.tsx
- src/styles/colors.scss
- src/styles/global.scss
- src/styles/pattern-library.scss
- Add contextual colors tokens:
```
// Contextual Colors ////////////////
--color-success: #cee8de;
--color-warning: #f6e0ba;
--color-error: #fee1e1;
```
- Adds contextual bg colors tokens:
```
// Backgrounds – Contextual
--bg-success: var(--color-success);
--bg-highlighted: var(--color-primary-0);
--bg-info: var(--color-secondary-1);
--bg-neutral: var(--color-neutral-1);
--bg-warning: var(--color-warning);
--bg-error: var(--color-error);
// Backgrounds – Discount range
--bg-discount-low: var(--bg-success);
--bg-discount-medium: var(--bg-warning);
--bg-discount-high: var(--bg-error);
```
- Updates borders tokens:
```
--border-width-0: 1px;
--border-width-1: 2px;
--border-width-2: 3px;
```
<em>Describe the steps …
> Chore: Add bg colors & updates border tokens

- cypress/integration/plp.test.js
- gatsby-ssr.js
- src/components/search/Filter/Filter.tsx
- src/components/search/Filter/index.ts
- src/components/sections/ProductGallery/ProductGallery.tsx
- src/hooks/useWindowDimensions.ts
This PR intends to add the `Filter` component.
> feat: Add Filter component

- src/components/sections/ProductDetails/ProductDetails.tsx
Change "Buy now" label to "Add to cart"
> feat: change Add to cart label

- src/components/product/ProductCard/ProductCard.tsx
- src/components/product/ProductCard/product-card.scss
- src/components/search/Sort/Sort.tsx
- src/components/search/Sort/sort.scss
- src/components/ui/Button/buttons.scss
- src/styles/typography.scss
- Extracts some general improvements from https://github.com/vtex-sites/base.store/pull/241
- Improves on `<Button variant="tertiary">` and aligns button icon
- Adds `title-small` class on `typography.scss`
|Before|After|
|-|-|
> Chore: update general styles

- src/components/cart/CartItem/CartItem.tsx
- src/components/cart/CartItem/cart-item.scss
- src/components/ui/QuantitySelector/QuantitySelector.tsx
This PR styles the CartItem following this [jira task](https://vtex-dev.atlassian.net/browse/FSSS-139).
The `CartItem` component already existed. I've added some styles to it. A small adjustment at the `QuantitySelector` component was necessary.
Access the preview. Add some items to the cart and open the cart. For now, it looks like this:
Thanks to @renatamottam for the help
> feat: Styles CartItem

- src/components/ui/Checkbox/Checkbox.tsx
- src/components/ui/Checkbox/checkbox.scss
- src/styles/utilities.scss
This PR styles the CheckBox component
Add a stylesheet for CheckBox and implement a style like the [Figma Prototype](https://www.figma.com/file/7gfHfIzqJAbLlmB7fs16gQ/Handoff-v3-(PLP)?node-id=1455%3A71627)
> feat: style checkbox

- gatsby-node.js
- store.config.js
In this PR integrate the My Account.
> feat: my-account integration

- cypress/integration/cart.test.js
- src/components/cart/CartSidebar/CartSidebar.tsx
- src/components/cart/OrderSummary/OrderSummary.tsx
Fix OrderSummary stats in CarSidebar, now when not exist products in cart the OrderSummary not render
> feat: Adjust checkout button

- gatsby-ssr.js
- src/components/sections/ProductDetails/ProductDetails.tsx
- src/sdk/analytics/platform/vtex.ts
Temporarily remove the SKU selector from the PDP
> [FSSS-155] Remove sku selector

- src/components/cart/CartItem/CartItem.tsx
- src/components/sections/ProductDetails/ProductDetails.tsx
- src/components/ui/QuantitySelector/QuantitySelector.tsx
This PR implements the QuantitySelector logic in Cart component using the updateItemQuantity function from useCart Hook
> [FSSS-134] Add quantity selector logic to the cart

- src/components/search/Filter/Facets.tsx
- src/components/search/Filter/Filter.tsx
This PR intends to optimize the `Filter` component code to reduce its cognitive complexity.
- [Cognitive complexity error](https://bytesofgigabytes.com/sonarqube/refactor-this-method-to-reduce-its-cognitive-complexity/)
> [FSSS-171] chore: Fix SonarQube error

- CHANGELOG.md
- src/components/cart/CartItem/CartItem.tsx
- src/components/cart/CartItem/cart-item.scss
- src/components/cart/CartSidebar/CartSidebar.tsx
- src/components/cart/CartSidebar/cart-sidebar.scss
- src/styles/layout.scss
This PR solves https://vtex-dev.atlassian.net/browse/FSSS-176 and https://vtex-dev.atlassian.net/browse/FSSS-183.
I've followed this to do the refactor:
- Removed <article> in favor of <Card> on CartItem.
- Removed <section> in favor of <List> for the list of Cart Items
- Favored `data-attributes` and tags instead of classes
- Removed the fixed height of the footer.
- Removed the footer of a class named body. 
Go to the preview, the cart sidebar should work the same way as before.
> [FSSS-176] Refactors minicart

- CHANGELOG.md
- store.config.js
Since we are changing the catalog of products. Some products didn't exist anymore. So we need to update our Lighthouse and Cypress URLs.
> Fix: Changes PDP url for lighthouse and cypress

- src/components/sections/Hero/Hero.tsx
- src/components/ui/Hero/hero.scss
Quick fix removing unecessary padding
> fix: image padding

- .github/workflows/main.yml
<em>Considering the context, what is the problem we'll solve? Where in VTEX's big picture our issue fits in? Write a tweet about the context and the problem itself.</em>
<em>Describe the steps with bullet points. Is there any external reference, link, or example?</em>
<em>Spread the knowledge: is this any content you used to create this PR that is worth sharing?</em>
- [] CHANGELOG entry added
> chore: Add lhci github action

- .github/workflows/main.yml
<em>Considering the context, what is the problem we'll solve? Where in VTEX's big picture our issue fits in? Write a tweet about the context and the problem itself.</em>
<em>Describe the steps with bullet points. Is there any external reference, link, or example?</em>
<em>Spread the knowledge: is this any content you used to create this PR that is worth sharing?</em>
- [] CHANGELOG entry added
> chore: Fix lhci workflow status check if the build failed or haven't finished yet

- src/styles/global/components.scss
> fix: Add missig skeleton element css

- CHANGELOG.md
Version created to be the last state before gatsby v4
Nothing should change.
> Updates CHANGELOG with 0.2.1 version

- CHANGELOG.md
- src/components/search/Filter/Filter.tsx
This PR intends to fix a bug for the mobile version, after applying filters the PLP loses scroll.
> Fix: No scroll bug after applying filters
