package.json
yarn.lock

This PR fixes that annoying issue with:
```
Plugin gatsby-plugin-next-seo is not compatible with your gatsby version 3.13.0 - It requires gatsby@^2
```

chore: Upgrade next seo

---

src/sdk/image/useImage.ts

I was trying to fix the wild blink of the SSRed product image on the pdp. However, while digging I've found  [this issue](https://github.com/gatsbyjs/gatsby/issues/32037) open on Gatsby and decided to add a todo in our code for us to remember to upgrade it once they fix this problem
Sonarqube bot will warn us about it and eventually we will upgrade gatsby-plugin-image and this problem will be fixed

chore: Fix Image SSR blink

---

package.json
yarn.lock

Removes unused `graphql-codegen-persisted-query-ids` dev dependency.

Removes unused graphql-codegen dev dependency

---

.eslintrc
src/components/product/ProductSummary/ProductSummary.tsx
src/components/sections/ProductGallery/ProductGallery.tsx
src/pages/[slug]/p.tsx
src/pages/{StoreCollection.slug}/[...].tsx
src/pages/{StoreProduct.slug}/p.tsx
src/sdk/cart/useBuyButton.ts
src/sdk/cart/validate.ts
src/sdk/error/ErrorBoundary/ErrorBoundary.tsx
src/sdk/graphql/useLazyQuery.ts
src/sdk/graphql/useQuery.ts
src/views/collection/Seo/hooks/useMetadata.ts
src/views/collection/Seo/index.tsx
src/views/home/Seo/hooks/useMetadata.ts
src/views/home/index.tsx
src/views/product/Seo/hooks/useMetadata.ts
src/views/product/hooks/useProduct.ts
src/views/product/index.tsx
src/views/search/Seo/index.tsx

To remove all `non-null assertions` found in the code and also turn back on two ESLint rules that are currently deactivated globally:
- `@typescript-eslint/no-use-before-define`
- `@typescript-eslint/no-non-null-assertion`
Also, I tried to remove as many unnecessary `any` types as I could, and now we don't get any warnings or errors when running `yarn lint` 😄 .
There should be no noticeable change in behavior, apart from extra error handling. To avoid runtime errors, some checks and logs were added in this PR when certain objects or properties are `null`. These cases would trigger a runtime error currently since non-null assertions are being used and these cases are not dealt with.
In the deploy preview below you should see no change in behavior. If you run `yarn lint` locally on this …

Remove non-null assertions and reactivate ESLint rules

---

gatsby-config.js

Uses the new VTEX_WEBOPS flag to know when building inside webops.
We used to do a hack to know when inside webops. We don't need that no more. We now use the default webops flag

chore: use webops flag

---

README.md
cypress/global.js
cypress/integration/a11y.test.js
cypress/integration/analytics.test.js
cypress/integration/cart.test.js
cypress/integration/performance.test.js
cypress/integration/plp.test.js
cypress/integration/search.test.js
cypress/integration/seo.test.js
gatsby-browser.js
gatsby-config.js
gatsby-ssr.js
lighthouserc.js
src/pages/{StoreCollection.slug}.tsx
src/sdk/cart/useCheckoutButton.ts
src/server/index.js
store.config.js
vtex.env

This PR merges all config into a single file. The main idea behind this PR is to make it easier for stores to setup their repo after forking this repo. Also, it makes it easier to automate this task
This PR merges config from lighthouse/cypress/api into a file called `store.config.js` and split it into sections. 
Make sure all features are working as intended

refactor: Merge configs into a single file

---

src/styles/pattern-library.scss
src/styles/typography.scss

After removing the small amount of CSS we had, we incurred in some lighthouse failures. This is a temporary fix for it, until we actually style the buttons and links.

Temporarily fix affordances on links and buttons

---

src/components/sections/ProductDetails/ProductDetails.tsx
src/components/ui/SkuSelector/SkuSelector.tsx
src/components/ui/SkuSelector/index.tsx
src/images/config.js

This PR intends to add the `SkuSelector` component (styles to be added in a future PR) to be rendered at the Product's details page.
This component is using the FastStore's `RadioGroup` component and its child components. It is meant to be used as a list of available (or not) variations of a product.

feat: SkuSelector component

---

src/components/ui/SkuSelector/SkuSelector.tsx
src/components/ui/SkuSelector/sku-selector.scss
src/pages/pattern-library.tsx
src/styles/colors.scss
src/styles/global.scss
stylelint.config.js

Styles our two types (for now) of SKU Selectors:
- Size
- Color
|Prototype|Image|Video|
|-|-|-|
|![image](https://user-images.githubusercontent.com/11613011/147496707-8c817da2-4f30-4bae-bf24-88cc44554e90.png)|![image](https://user-images.githubusercontent.com/11613011/147496750-3097a25e-4567-4e79-9eb5-bc2c30ed8d8f.png)|https://user-images.githubusercontent.com/11613011/147496628-c4f3e658-3041-49be-9a59-2f92bb616975.mov|
You can see it working on the `/pattern-library` page

Feat: Style SKU Selectors

---

src/components/sections/ProductDetails/ProductDetails.tsx
src/components/ui/SkuSelector/SkuSelector.tsx
src/components/ui/SkuSelector/sku-selector.scss
src/pages/pattern-library.tsx

This PR intends to rename the SkuSelector's `size` variant to `label` to keep it more generic.

fix: Rename SkuSelector's 'size' variant to 'label'

---

src/components/cart/CartToggle/CartToggle.tsx
src/components/cart/CartToggle/cart-toggle.scss
src/components/common/SearchInput/SearchInput.tsx
src/components/sections/BannerText/banner-text.scss
src/components/sections/Hero/Hero.tsx
src/components/ui/Alert/Alert.tsx
src/components/ui/Hero/hero.scss
src/components/ui/Link/link.scss
src/pages/pattern-library.tsx
src/styles/global.scss
src/styles/scaffold.scss
src/styles/utilities.scss

- Updates icons import from phosphor lib
- Fixes some stylesheets syntax issues
- Adds `px to rem` function
- Creates `scaffold.scss` file. Maybe we could import this file whenever we need to use `include media` or `px to rem` function. I don't like this approach but I couldn't find a work around for now.

chore: adds general updates to `main-styled`

---

src/components/sections/ProductDetails/ProductDetails.tsx
src/components/ui/Button/Button.tsx
src/components/ui/Button/buttons.scss
src/components/ui/BuyButton/BuyButton.tsx
src/components/ui/BuyButton/buy-button.scss
src/pages/pattern-library.tsx
src/styles/colors.scss
src/styles/pattern-library.scss
src/styles/typography.scss
src/styles/utilities.scss
stylelint.config.js

Styles our three types of buttons:
- BuyButton
- Primary
- Secondary
|Type|Image|Video|
|-|-|-|
|BuyButton|![image](https://user-images.githubusercontent.com/11613011/147288668-8ab00564-832d-49e3-b2e7-6c5ec696ca80.png)|https://user-images.githubusercontent.com/11613011/147288232-614e9a16-530a-4efc-9eb3-6697280539bb.mov|
|Primary|![image](https://user-images.githubusercontent.com/11613011/147288760-c6bb2d71-aca7-4fac-bfec-73b3e4a869d9.png)|https://user-images.githubusercontent.com/11613011/147288822-cacef365-25a3-4bd0-9fb9-24a753966bba.mov|
|Secondary|![image](https://user-images.githubusercontent.com/11613011/147289096-845a13ce-f282-427e-aec7-bb2a3662362b.png)|https://user-images.githubusercontent.com/11613011/147289190-3d2467c8-68cf-468e-b2fb-697bdcb6f401.mov|
You can see it working on …

Feat: Style Buttons

---

@generated/graphql/index.ts
src/components/sections/ProductDetails/ProductDetails.tsx
src/components/ui/Breadcrumb/Breadcrumb.tsx
src/components/ui/Breadcrumb/index.tsx

This PR intends to add the basic structure of the **Breadcrumb** component to the Base Store (styling will be covered in a future PR). For prioritization concerns, this PR will also not implement the extra links (`...` link), this will be tackled in a future PR.
The component will basically `map` the items in the **breadcrumbList** to render them as `Links`
The component is displayed in the PDP page, and it can be tested by accessing the links in the breadcrumb.

feat(ui): Add Breadcrumb

---

src/components/sections/ProductDetails/ProductDetails.tsx
src/components/ui/Breadcrumb/Breadcrumb.tsx
src/components/ui/Breadcrumb/breadcrumb.scss

This PR styles the Breadcrumb component
Add a stylesheet for Breadcrumb and implement a style like the [Figma Prototype](https://www.figma.com/file/wS0Kek1aSzIRl20jdtnSsL/Alpha-Version?node-id=0%3A1)

Style breadcrumb style

---

src/components/common/Navbar/Navbar.tsx
src/components/common/Navbar/navbar.scss
src/components/ui/Button/Button.tsx
src/components/ui/Button/LinkButton.tsx
src/components/ui/Button/buttons.scss
src/components/ui/Button/index.tsx
src/components/ui/SignInLink/SignInLink.tsx
src/components/ui/SignInLink/index.ts
src/pages/pattern-library.tsx

This PR styles the SignInLink component
Add a stylesheet for SignInLink and implement a style like the [Figma Prototype](https://www.figma.com/file/wS0Kek1aSzIRl20jdtnSsL/Alpha-Version?node-id=0%3A1)

style: Add sigin link styles

---

cypress/integration/analytics.test.js
src/components/common/Navlinks/Navlinks.tsx
src/components/common/SearchInput/SearchInput.tsx

This PR intends to add the `search` event to the analytics events layer. 
Ps. This PR is replacing the #97.
Every time a term is searched in the `SearchInput` component, the `sendAnalyticsEvent` is trigged and the `search` event is added to the dataLayer.
Tests in `analytics.test.js` file will simulate the steps of a search scenario. Just run `yarn test`. 
GA4 reference about [Search event](https://developers.google.com/analytics/devguides/collection/ga4/reference/events#search)

feat: Add search event to Analytics

---

src/components/product/ProductCard/ProductCard.tsx
src/components/ui/Price/Price.tsx
src/components/ui/SROnly/SROnly.tsx
src/components/ui/SROnly/index.tsx
src/components/ui/SROnly/sr-only.scss

- "sr-only" means "screen reader only"
- Introducing this technique for hiding content when other approaches are unavailable. We should use this component to give extra context that could be visibly hidden in the interface.
- Aims to deliver better experience for screen readers users.
- Visually, nothing changes.
https://user-images.githubusercontent.com/3356699/148112592-4223b85b-2051-419d-b3b0-e3e000d43e47.mov
- https://webaim.org/techniques/css/invisiblecontent/

feat: Adds SROnly component

---

src/components/product/ProductCard/ProductCard.tsx
src/components/product/ProductCard/index.tsx
src/components/product/ProductGrid/ProductGrid.tsx
src/components/product/ProductSummary/index.tsx

- Renames `ProductSummary` component to `ProductCard`
- In order to adopt a common language for the team
- https://www.notion.so/vtexhandbook/FastStore-Components-5327450cefcc43a59b723ddc6869dd6f

Chore: Renames ProductSummary to ProductCard

---

cypress/integration/analytics.test.js
cypress/support/commands.js
package.json
yarn.lock

Fix analytics events with intermittent errosr. Adding [cypress-wait-until](https://www.npmjs.com/package/cypress-wait-until) dependence and fixing dataLayerHasEvent

Fix: Adjust Data Layer has event

---

src/components/sections/Hero/Hero.tsx
src/components/sections/Incentives/incentives.scss
src/components/ui/Hero/hero.scss
src/styles/global.scss
src/styles/grid.scss
src/styles/typography.scss

Improve Hero and Incentives heights to adapt better on all devices.
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/11613011/149535352-e6137d2e-61de-413d-8b4d-8b55770b6e2c.png)|![image](https://user-images.githubusercontent.com/11613011/149535394-5209a33f-d7ac-4ee5-a19b-334ab6208dbb.png)|
|![image](https://user-images.githubusercontent.com/11613011/149535499-6f56966e-ad89-46f0-91fd-1472e1287831.png)|![image](https://user-images.githubusercontent.com/11613011/149535574-221f1684-29e3-40b0-a3d4-03fffc9a3c6e.png)|
|![image](https://user-images.githubusercontent.com/11613011/149542387-f3351c61-c4c0-4349-a219-f65743d96553.png)|![image](https://user-images.githubusercontent.com/11613011/149542422-86252e9c-300f-4cef-9678-d41f411dac55.png)| …

Feat: Sizing improvements (Hero + Incentives)

---

gatsby-ssr.js

Last PR merged to `master` (#228) was passing CI, but [failed](https://github.com/vtex-sites/base.store/runs/4817817480) once merged.
This PR removes the `preconnect` because there was the following warning:

Fix Lighthouse check due to an unused pre-connection

---

src/Layout.tsx
src/styles/global.scss
src/styles/pages/index.scss

Another attempt to fix PLP's Cumulate Layout Shift plaguing `main-style` and its other branches.
On the PLP page load, the footer starts occupying a big part of the viewport and it has some internal layout shifts in the incentives list area, as well as the transformation of the footer links into the accordion.
Incentives|Accordion
-|-
This temporary fix increases the minimum height of the main element so it pushes the footer the minimum amount to be below the fold. That is possible because the height of the alert and navbar don't change frequently. It's believed that when https://github.com/vtex-sites/base.store/pull/240 lands, we won't need this fix and can remove it. Or when we implement page skeletons in the future.
The Lighthouse CI check passes.
Before|After
-|-
- Another attempt to …

Fix: Attempt to fix PLP Lighthouse CLS issue

---

src/components/sections/ProductDetails/ProductDetails.tsx
src/pages/{StoreProduct.slug}/p.tsx

Remove a visual bug caused by the product name appearing above the breadcrumb on the PDP.
It was an `h1` that was moved inside the `ProductTitle`.
Before|After
-|-
Visit any PDP on the deploy preview (e.g. https://preview-251--base.preview.vtex.app/sleek-steel-table-58621790/p/).

Remove duplicate product name on PDP

---

package.json
src/sdk/analytics/platform/vtex.ts
yarn.lock

Currently cypress runs in two different versions on local development and on the CI. This PR fix the base.store version to '6.6.0'

fix: change cypress version

---

src/components/common/Footer/FooterLinks.tsx
src/components/common/Footer/footer.scss
src/components/search/Filter/Filter.tsx
src/components/search/Filter/filter.scss
src/components/ui/Accordion/Accordion.tsx
src/components/ui/Accordion/AccordionItem.tsx
src/components/ui/Accordion/accordion.scss

- Extracts accordion base style from `Footer.scss` and `Filter.scss`
- Replaces Accordion on Footer and Filter
- Visual adjusts on Filter component
PS: The Filter's footer (buttons area) still flicks a little bit on mobile, but it will be solved when we replace the Modal for the [SlideOver component](https://github.com/vtex-sites/base.store/pull/262)
[FSSS-151 Styles Accordion and Replace](https://vtex-dev.atlassian.net/jira/software/projects/FSSS/boards/632?selectedIssue=FSSS-151)

[FSSS-151] Feat: Styles Accordion and Replace

---

store.config.js

This PR changes the store url to vtexfaststore.com, our official website for base.store.

chore: change store url to vtexfaststore.com

---

gatsby-ssr.js

Sometimes PDP's Lighthouse check will fail due to [errors being logged to the browser's console](https://github.com/vtex-sites/base.store/runs/4899927947#:~:text=%E2%9C%98-,errors%2Din%2Dconsole,-failure%20for%20minScore):
> TypeError: Cannot read properties of undefined (reading 'sendEvent')
at Proxy.window.sendrc (eval at le (077a6614-0b37-4599-9ad7-70338f3e2ddb:2:3612), <anonymous>:4:66)
> 
> https://base.vtex.app/sleek-metal-pizza-24041857/p/
Visit this PDP for the [previous version](https://sfj-63cf751--base.preview.vtex.app/sleek-metal-pizza-24041857/p/) and you should see an error on the console. Compare to the PDP in the [next version](https://sfj-97024cd--base.preview.vtex.app/sleek-metal-pizza-24041857/p/) and the error is gone. …

Fix Lighthouse PDP flaky error in console failure

---

src/components/cart/CartSidebar/CartSidebar.tsx
src/components/cart/EmptyCart/EmptyCart.tsx

- Pass `onDismiss` function for `EmptyState` component, so who controls what to do when `Start Shopping` is clicked is the parent.
- It fixes the "locked" layout issue.
|Before|
|-|
|After|
|-|
Open MiniCart and press `Start Shopping`. Now try to scroll the page.

Fix: MiniCart - Empty State

---

gatsby-config.js

We should see _FastStore_ on the tabs bar instead of _Fashion Store_.

[FSSS-166] Chore: Updates metatags

---

README.md

- Updates css example on readme file.
- There is no space between the class and the data-atribute 
- It should be:
```css
.primary[data-store-button] {
background: blue;
}
.secondary[data-store-button] {
background: pink;
}
```

Fix: Fixes css example on readme

---

cypress/integration/plp.test.js
src/components/search/Filter/Filter.tsx
src/components/sections/ProductGallery/ProductGallery.tsx
src/pages/{StoreCollection.slug}.tsx

This PR intends to fix `Filter`s wrong behaviors, mainly for the mobile version. For instance, the component wasn't clearing all facets when requested or applying the right facets.

chore: Filter component's fixes

---

package.json
yarn.lock

This PR bumps the version of the nginx plugin so the build doesn't break

fix: bump nginx plugin version to unbreak store

---

src/components/ui/QuantitySelector/QuantitySelector.tsx

Fix a [SonarQube warning](https://github.com/vtex-sites/base.store/runs/5025104180#:~:text=15M/61M%0AINFO%3A%20%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D-,ANNOTATIONS,-Check%20warning%20on) in a piece of the code by following its suggestion of removing a temporary variable.
The last commit should not have SonarQube trigger the warning anymore.
Before|After
-|-

Fix a SonarQube warning

---

src/components/common/Footer/Footer.tsx
src/components/common/Navbar/Navbar.tsx
src/components/product/ProductCard/ProductCard.tsx
src/components/product/ProductGrid/ProductGrid.tsx
src/components/sections/Hero/Hero.tsx
src/components/sections/ProductShelf/ProductShelf.tsx
src/components/sections/ProductTiles/ProductTiles.tsx
src/components/ui/Alert/Alert.tsx
src/components/ui/Badge/DiscountBadge.tsx
src/components/ui/Breadcrumb/Breadcrumb.tsx
src/components/ui/Breadcrumb/BreadcrumbWrapper.tsx
src/components/ui/Breadcrumb/index.tsx
src/components/ui/Price/Price.tsx
src/components/ui/ProductTitle/ProductTitle.tsx
src/components/ui/QuantitySelector/QuantitySelector.tsx
src/hooks/useSearchParams.ts
src/pages/{StoreCollection.slug}.tsx
src/pages/{StoreProduct.slug}/p.tsx

This PR fixes some inappropriate rerenders with memo function and removing  peer dependencies from hooks. To observe this rerenders I used the [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi) with the option "Highlight updates when components render" checked.
||Before|After|
|-|-|-|
| PLP | ![plp-old](https://user-images.githubusercontent.com/51174217/152550694-82434ab6-89b8-4a1e-8a5a-0c6746cd0b7a.gif) | ![plp](https://user-images.githubusercontent.com/51174217/152547097-086176d8-737f-44d0-8cc2-c9ad12b3fddd.gif) |
| HOME |  ![home-old](https://user-images.githubusercontent.com/51174217/152549819-a1ceb67c-e9e3-46b5-a359-13200f25b587.gif) | ![home](https://user-images.githubusercontent.com/51174217/152547727-06c8c9d5-f8 …

[FSSS-172] Fix/Adjust inappropriate rerenders

---

src/components/sections/ProductGallery/product-gallery.scss
src/components/sections/ProductListing/product-listing.scss
src/constants.ts

24 items per page is just a HUGE number. Reduces this number to 12 to fix the lighthouse warning of too complex HTML

fix: PLP complexity

---

CHANGELOG.md
src/components/common/Navbar/Navbar.tsx
src/hooks/useAllCollections.ts

As title says, it removes an unnecessary map function.
`map` decreases overall app performance. Let's try to keep them to a minimal

chore: Remove unnecessary map

---

CHANGELOG.md
cypress/integration/analytics.test.js
cypress/integration/search.test.js
src/components/common/Navbar/Navbar.tsx
src/components/common/Navbar/navbar.scss
src/components/common/SearchInput/SearchInput.tsx

This PR Implements the expanded mode of `Searchbar` in mobile devices.
In mobile devices, when magnifier Icon is clicked the Searchbar should expand with animation, and when Arrow Left Icon is clicked the searchbar should retract.
For add this behaviour, the searchbar test was modified

feat: Add expanded search state

---

CHANGELOG.md
src/components/cart/CartItem/CartItem.tsx
src/components/search/SuggestionProductCard/SuggestionProductCard.tsx
src/components/sections/Hero/Hero.tsx
src/components/ui/ImageGallery/ImageGallery.tsx
src/components/ui/SkuSelector/SkuSelector.tsx

Improves image processing by using great thumbor features. 
Thumbor has amazing tools regarding image cropping and resizing. To know more: https://thumbor.readthedocs.io/en/latest/usage.html#image-endpoint.  
We were extensively using one of these features called `fit-in`. This property is ok when the images behave badly, however, our UI thinks the images are nice and have the same aspect ratio. In this case we can drop out of using `fit-in` and save some bytes out of the images.
Also, another optimization this PR brings is to render img components once, by moving the creation of the `breakpoints` array outside the rendering cycle of the app. This should save some re-renders too.
Finally, hero's aspect-ratio image was wrong. On moto g4 the right aspect ratio was 3/2, not 2. The fix makes …

chore: Improve images

---

CHANGELOG.md
src/components/search/SuggestionProductCard/SuggestionProductCard.tsx
src/components/search/SuggestionProductCard/suggestion-product-card.scss
src/components/search/Suggestions/Suggestions.tsx
src/components/search/Suggestions/SuggestionsTopSearch.tsx
src/components/search/Suggestions/index.ts
src/components/search/Suggestions/suggestions.scss

This PR intends to add the `Suggestions` component. The purpose of this component is to encapsulate autocomplete suggestions and suggested products.
Note: The component has mock data as the integration will be done later.
Since the component will be part of the `Suggestion`'s dropdown component, we don't have a specific place to render the component yet.
But one option is to render it in the `Navbar` component as shown below:
```
// line 84
<SearchInput
onBlur={() => setSearchExpanded(false)}
onFocus={() => setSearchExpanded(true)}
/>
```
```
// line 110
{searchExpanded && <Suggestions />}
```
[FSSS 191 - Search Suggestions component](https://vtex-dev.atlassian.net/browse/FSSS-191)

feat: Search Suggestions component

---

CHANGELOG.md
src/components/cart/CartSidebar/cart-sidebar.scss
src/components/ui/Badge/Badge.tsx
src/components/ui/Badge/badge.scss

This PR intends to add a new `Badge` variant called `interactive`. This will be useful when the user needs an action to close/remove badges.
**Default interactive badge:**
**Small interactive badge:**
[FSSS 204 - Creates Badge Interactive variation](https://vtex-dev.atlassian.net/browse/FSSS-204?atlOrigin=eyJpIjoiZDgzY2IzZmU1ODY5NGY1YjlkNTljODlhOTQ5ZGZlMTAiLCJwIjoiaiJ9)

feat: Adds new Badge interactive variation

---

CHANGELOG.md
src/components/cart/CartItem/CartItem.tsx
src/components/cart/CartItem/cart-item.scss

This PR intends to fix the size of `CartItem`'s product's title and image.
Before, for cases where the product title is long, the product image was shrunk:
With the changes, this was fixed by truncating the product title (maximum of two lines) and the image size remains fixed.
[FSSS 213 - Fix image and product's title size on `CartItem`](https://vtex-dev.atlassian.net/browse/FSSS-213)

fix: CartItem's product's title and image size fixes

---

CHANGELOG.md
src/components/ui/Button/buttons.scss

For some reason, the button has a `default` cursor, but the "normal" button cursor is a pointer and not the default.
<em>Describe the steps with bullet points. Is there any external reference, link, or example?</em>
<em>Spread the knowledge: is this any content you used to create this PR that is worth sharing?</em>

Fix the Button cursor

---

CHANGELOG.md

This PR updates the CHANGELOG so it matches it's [March Release Notes](https://faststore.dev/releases/2022/04/01/basestore). 
I've also added the identifier of the PR to each CHANGELOG entry so we don't need to rely on git blame to identify the PR responsible for the entry.
Each entry that was merged before #392 was added to the 0.2.0 section. A new [Github release](https://github.com/vtex-sites/base.store/releases/tag/v0.2.0) was also added to reflect this state.
Each entry after this is still in the Unreleased section.
Check if the CHANGELOG makes sense and doesn't have any wrong information.
https://keepachangelog.com/en/1.0.0/

Updates CHANGELOG to match base.store's March Release Notes

---

src/sdk/ui/modal/Provider.tsx
src/styles/global/components.scss

Adds missing CSS import from https://github.com/vtex-sites/base.store/pull/426

Fix: Adds global css import for Modal Provider

---

CHANGELOG.md
src/components/common/Navbar/navbar.scss

This PR is going to tweak the BaseStore logo on small mobile devices (e.g. Moto G4)
|Before|After|
|-|-|
|<img width="556" alt="image" src="https://user-images.githubusercontent.com/10616243/161819101-2cbf3522-8a18-45f4-a954-d9c0726ea144.png">|<img width="553" alt="image" src="https://user-images.githubusercontent.com/10616243/161819197-c42e6f7a-c170-4a3b-864b-86ca97cc96ad.png">|
Just used a media query to set a right margin on devices smaller than a tablet. 
```
@include media("<tablet") {
margin-right: var(--fs-spacing-5);
}
```
Just run the preview in mobile version and choose a small layout.
Related to #447
Problem caught by @tlgimenes. Tks ✨ 
[How to make a good Changelog](https://keepachangelog.com/en/1.0.0/#:~:text=The%20latest%20version%20comes%20first) via @filipewl 
<em>You may …

fix: Tweak logo on mobile

---

CHANGELOG.md
src/components/common/Navbar/navbar.scss

Fixes the search input margin-left mentioned previously [here](https://github.com/vtex-sites/base.store/pull/455#pullrequestreview-932314333).
|Before|After|
|-|-|
|![M41MNHL4OQ](https://user-images.githubusercontent.com/11325562/161831131-a306b615-009e-4a33-b9a8-c907fb173db4.gif)|![Qmm3uRHlMc](https://user-images.githubusercontent.com/11325562/161831253-a4cef7a8-82c4-4cdb-b720-490e6c6998f4.gif)|
Compare the preview version with the older versions.

Fixes search input margin left

---

CHANGELOG.md
src/styles/global/layout.scss

This PR fixes the spaces (padding/margin) on elements that use the `layout__section` class.
We changed the spacings from margin to padding on #464 due to a problem with the `box-shadow` on the `product-card`. At first glance, it was good, but it causes a regression with PDP due to margin collapse. So we just change the style from `padding-top` to `margin-top` again and it works as expected.
|Before|After|
|-|-|
|<img width="1399" alt="Screen Shot 2022-04-08 at 12 21 11" src="https://user-images.githubusercontent.com/11325562/162472892-b059a371-a8f1-4578-a94b-4d509295214b.png">|<img width="1400" alt="Screen Shot 2022-04-08 at 12 19 03" src="https://user-images.githubusercontent.com/11325562/162472362-2bfc5048-a69f-40d8-8885-5dda308179b7.png">|
The elements with the layout__section class …

Fix: Tweaks layout section spacings

---

CHANGELOG.md
src/components/sections/Incentives/Incentives.tsx
src/components/sections/Incentives/IncentivesFooter.tsx
src/components/sections/Incentives/IncentivesHeader.tsx
src/components/sections/Incentives/incentivesMock.js
src/pages/index.tsx

This PR aims to keep the `Incentives` component synced after changes made in the forked project [storeframework](https://github.com/vtex-sites/storeframework.store/pull/47).
This PR used cherry-pick to copy code updates from [storeframework](https://github.com/vtex-sites/storeframework.store/pull/47), and mocked the Incentives in `incentivesMock.js `file.
Nothing special to be tested, just run the project and see the `IncentivesHeader` and `IncentivesFooter` working properly.
- Storeframework [PR](https://github.com/vtex-sites/storeframework.store/pull/47) with final integration with CMS
- Related [Jira Task](https://vtex-dev.atlassian.net/browse/FSSS-261)
- Git cherry-pick [documentation](https://git-scm.com/docs/git-cherry-pick)

Adjust Incentives to render CMS data

---

CHANGELOG.md
src/styles/pages/layout.scss

Fix styling issue on Regionalization Modal by adding the missing imports in layout.scss

Add missing styles to layout.scss
